import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from scipy.special import spherical_jn, spherical_yn
import cartopy.crs as ccrs

# ==========================================
# 1. Zimmer et al. (2000) Bessel Engine
# ==========================================
def calculate_Q_complex(f, sigma, r1_km, r2_km, R_target_km):
    """
    Calculates the complex response Q = A*exp(i*phi) for an induced dipole
    generated by a conducting shell (ocean). Based on Zimmer et al. (2000).
    R_target_km: The radius where the field is measured (e.g., surface, spacecraft).
    """
    mu0 = 4 * np.pi * 1e-7
    omega = 2 * np.pi * f
    k = np.sqrt(-1j * mu0 * sigma * omega)
    
    a = r2_km * 1000  # Outer radius (top of ocean)
    b = r1_km * 1000  # Inner radius (bottom of ocean)
    
    ka = k * a
    kb = k * b
    
    j1_ka = spherical_jn(1, ka)
    y1_ka = spherical_yn(1, ka)
    j1_kb = spherical_jn(1, kb)
    y1_kb = spherical_yn(1, kb)
    
    # [z * j_n(z)]' derivatives
    dj_dz_ka = spherical_jn(1, ka) + ka * spherical_jn(1, ka, derivative=True)
    dy_dz_ka = spherical_yn(1, ka) + ka * spherical_yn(1, ka, derivative=True)
    dj_dz_kb = spherical_jn(1, kb) + kb * spherical_jn(1, kb, derivative=True)
    dy_dz_kb = spherical_yn(1, kb) + kb * spherical_yn(1, kb, derivative=True)

    # Shell constant matching matrix logic for n=1
    alpha = dj_dz_kb / dy_dz_kb
    
    # Ratio of induced (s) to primary (p) field defined at the surface (r=a)
    Q_surface = ( (ka * j1_ka - dj_dz_ka) - alpha * (ka * y1_ka - dy_dz_ka) ) / \
                ( (ka * j1_ka + dj_dz_ka) - alpha * (ka * y1_ka + dy_dz_ka) )

    # Scale Q to the measurement altitude (using 1/r^3 dependence for dipole)
    # R_E is the reference radius (usually surface r2)
    Q_measured = Q_surface * (a / (R_target_km * 1000))**3
    
    return Q_measured

# ==========================================
# 2. Physics & System Definition
# ==========================================
# Physical Constants & Properties
R_E = 1560.0              # km (Europa Radius)
ice_thickness = 20.0     # km
ocean_thickness = 100.0  # km
sigma_ocean = 3.0        # S/m (Earth seawater conductivity)
flyby_altitude_km = 100.0 # Flyby measurement altitude
perfect_cond = True

# Calculation definitions
r2 = R_E - ice_thickness # Top of ocean (R_outer)
r1 = r2 - ocean_thickness# Bottom of ocean (R_inner)
R_obs = R_E + flyby_altitude_km # Observer distance

period_synodic = 11.1 * 3600 # seconds
freq = 1 / period_synodic

# B-field vectors (using spherical polar coordinates: Radial, Theta, Phi)
# We assume the background field is oriented along the Jupiter Z-axis (normal to the orbit plane)
# In Europa's standard 'E' system, Jupiter's rotating field sweeps past with strong By/Bx.
# For simplicity, let's assume B_bg is aligned with the planetary Y-axis at this instant.
B_bg_xyz = np.array([0, 210.0, 0]) # nT (Snapshot in time)
B0 = np.linalg.norm(B_bg_xyz)

# Calculate the complex induction response A*exp(i*phi)
Q_val = calculate_Q_complex(freq, sigma_ocean, r1, r2, R_obs)
A = np.abs(Q_val)
phi_rad = np.angle(Q_val)


if perfect_cond:
    A = 1.
    phi_rad = 0.

print(f"Zimmer (n=1) Response: A={A:.3f}, phi={np.degrees(phi_rad):.1f} deg")

# ==========================================
# 3. Create Spatial Grid (Mollewide)
# ==========================================
res = 5  # Resolution in degrees
lons_deg = np.arange(-180, 180 + res, res)
lats_deg = np.arange(-90, 90 + res, res)
Lon, Lat = np.meshgrid(lons_deg, lats_deg)

# Spherical to Cartesian (for field vector manipulation)
# Assuming EPHI is aligned with Lon, ETHETA with Lat (measured from equator)
R_norm = R_obs / R_E # Normalized observer radius
phi = np.radians(Lon)
theta = np.radians(90 - Lat) # Co-latitude from North Pole

# Observation points in Cartesian space (Europancentric)
x_obs = R_obs * np.sin(theta) * np.cos(phi)
y_obs = R_obs * np.sin(theta) * np.sin(phi)
z_obs = R_obs * np.cos(theta)

# Induced Dipole Moment M
# The moment vector points opposing B_bg. M = 2 * pi * R_E^3 * Q * B_bg
# We use a unit moment oriented with Q.
M_vector = -Q_val * B_bg_xyz # Complex moment aligned opposing B_bg
M_vector = M_vector.real # Taking real part for instantaneous snapshot

# Calculate B_ind (Dipole field) at all grid points
# B = (mu0/4pi) * (3(M.r)r/r^5 - M/r^3). Normalized to match Zimmer model form.
R_vec = np.stack([x_obs, y_obs, z_obs], axis=-1)
R_mag = np.linalg.norm(R_vec, axis=-1)
R_unit = R_vec / R_mag[..., None]

M_dot_R = np.sum(M_vector * R_vec, axis=-1)
# B_ind equation (simplified form, matching Q scaling)
B_ind_xyz = ( (3 * M_dot_R[..., None] * R_vec) / R_mag[..., None]**2 - M_vector ) * (R_E / R_obs)**3

# Superimpose fields: B_total = B_bg + B_ind
B_total_xyz = B_bg_xyz + B_ind_xyz
B_total_mag = np.linalg.norm(B_total_xyz, axis=-1)

# ==========================================
# 4. Plotting (2-Panel Layout)
# ==========================================
fig = plt.figure(figsize=(16, 7))

# Panel (a): Conductivity Profile
ax1 = fig.add_subplot(1, 2, 1)
z_norm = np.linspace(0, 1, 1000)
sigma_profile = np.zeros_like(z_norm)

# Define conductivity zones based on input parameters
# Normalized radius from center
idx_core = (z_norm <= (r1 / R_E))
idx_ocean = ((z_norm > (r1 / R_E)) & (z_norm <= (r2 / R_E)))
idx_ice = (z_norm > (r2 / R_E))

if perfect_cond:
    idx_ocean =  (z_norm <= (R_E))

sigma_profile[idx_core] = 0.0 # Insulating core
sigma_profile[idx_ocean] = sigma_ocean
sigma_profile[idx_ice] = 0.0  # Insulating ice


ax1.plot(z_norm, sigma_profile, 'k', linewidth=2.5, label='$\sigma$ Profile')
ax1.fill_between(z_norm, sigma_profile, color='royalblue', alpha=0.3)

# Annotation/formatting
ax1.set_title("(a) Subsurface Conductivity $\sigma$ Profile", fontsize=14, pad=15)
ax1.set_xlabel("Normalized Radius ($r/R_E$)", fontsize=12)
ax1.set_ylabel("Conductivity (S/m)", fontsize=12)
ax1.set_xlim(0, 1.1)
ax1.set_ylim(-0.1, sigma_ocean + 0.5)
ax1.set_aspect(1.0 / ax1.get_data_ratio() * 0.7) # Adjust aspect

# Label zones
if not perfect_cond:
    ax1.axvspan(0, r1/R_E, color='grey', alpha=0.15)
    ax1.axvspan(r1/R_E, r2/R_E, color='dodgerblue', alpha=0.15)
    ax1.axvspan(r2/R_E, 1.0, color='lightgrey', alpha=0.3)
    ax1.text(0.3, 0.5, 'Silicate Core\n(Insulating)', rotation=90, va='center', ha='center', fontsize=9, color='k')
    ax1.text(1.02, 0.5, 'Ice Shell\n(Insulating)', rotation=270, va='center', ha='center', fontsize=9)
ax1.text((r1+r2)/(2*R_E), sigma_ocean + 0.1, 'Conducting Ocean', ha='center', fontsize=10, color='b')

ax1.grid(True, linestyle='--', color='lightgrey')


# Panel (b): Mollweide Spatial Map (Cartopy)
ax2 = fig.add_subplot(1, 2, 2, projection=ccrs.Mollweide())

# Define the colorscale centered around the background field strength B0
# Define deviations
B_diff = B_total_mag - B0
max_dev = max(abs(B_diff.min()), abs(B_diff.max()))
norm = mcolors.TwoSlopeNorm(vmin=B0 - max_dev, vcenter=B0, vmax=B0 + max_dev)

# Plot the field magnitude data
# NOTE: We use B_total_mag, color it by magnitude, using norm centered at B0
contour = ax2.pcolormesh(Lon, Lat, B_total_mag, transform=ccrs.PlateCarree(), 
                          cmap='bwr', norm=norm, shading='gouraud')

# Map elements
ax2.set_title(f"(b) Induced Field Magnitude $|B|$ for {flyby_altitude_km}km Flyby", fontsize=14, pad=15)
#ax2.coastlines(resolution='110m', color='grey', linewidth=0.8) # (Europa coastlines are just a sphere)

# Gridlines formatting
gl = ax2.gridlines(crs=ccrs.PlateCarree(), draw_labels=True,
                  linewidth=1, color='grey', alpha=0.5, linestyle='--')
gl.top_labels = False
gl.right_labels = False
gl.xlabel_style = {'size': 9, 'color': 'grey'}
gl.ylabel_style = {'size': 9, 'color': 'grey'}

# Colorbar
cbar = fig.colorbar(contour, ax=ax2, orientation='horizontal', fraction=0.06, pad=0.1)
cbar.set_label('Total Magnetic Field Strength (nT)', fontsize=11)
cbar.set_ticks([B0 - max_dev, B0, B0 + max_dev])
cbar.set_ticklabels([f'{B0 - max_dev:.1f} (Min)', f'{B0:.1f} ($B_{{bg}}$)', f'{B0 + max_dev:.1f} (Max)'])

plt.tight_layout()
plt.show()